# Generated by Django 4.1.7 on 2023-02-17 14:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(help_text="Enter author's name", max_length=100, verbose_name="Author's name")),
                ('last_name', models.CharField(help_text="Enter author's surname", max_length=100, verbose_name="Author's surname")),
                ('date_of_birth', models.DateField(blank=True, help_text='Enter date of birthday', null=True, verbose_name='Date of birthday')),
                ('date_of_death', models.DateField(blank=True, help_text='Enter date of death', null=True, verbose_name='Date of death')),
            ],
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text="Enter book's title", max_length=100, verbose_name="Book's title")),
                ('summary', models.TextField(help_text='Enter short description book', max_length=1000, verbose_name="Book's annotation")),
                ('isbn', models.CharField(help_text='Must contain 13 chars', max_length=13, verbose_name="Book's ISBN")),
                ('author', models.ManyToManyField(help_text="Choose book's author", null=True, to='catalog.author', verbose_name="Book's author")),
            ],
        ),
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Enter genre book', max_length=200, verbose_name='Genre book')),
            ],
        ),
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lang', models.CharField(help_text='Enter book language', max_length=20, verbose_name='Book language')),
            ],
        ),
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="Enter book's copy status", max_length=20, verbose_name='Status copy book')),
            ],
        ),
        migrations.CreateModel(
            name='BookInstance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inv_nom', models.CharField(help_text="Enter copy's inventory number", max_length=20, null=True, verbose_name='Inventory number')),
                ('imprint', models.CharField(help_text='Enter publishing house and release year', max_length=200, verbose_name='Publishing house')),
                ('due_back', models.DateField(blank=True, help_text="Enter end of status's term", null=True, verbose_name='Date of status end')),
                ('book', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='catalog.book')),
                ('status', models.ForeignKey(help_text="Changes copy's status", null=True, on_delete=django.db.models.deletion.CASCADE, to='catalog.status', verbose_name="Book copy's status")),
            ],
        ),
        migrations.AddField(
            model_name='book',
            name='genre',
            field=models.ForeignKey(help_text='Choose genre  for book', null=True, on_delete=django.db.models.deletion.CASCADE, to='catalog.genre', verbose_name="Book's genre"),
        ),
        migrations.AddField(
            model_name='book',
            name='language',
            field=models.ForeignKey(help_text="Choose book's language", null=True, on_delete=django.db.models.deletion.CASCADE, to='catalog.language', verbose_name="Book's language"),
        ),
    ]
