# Generated by Django 4.1.7 on 2023-02-17 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='author',
            field=models.ManyToManyField(help_text="Choose book's author", to='catalog.author', verbose_name="Book's author"),
        ),
    ]
